use std::collections::HashMap;
use std::sync::{Mutex, OnceLock};

use crate::app_preferences::UiLocale;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(super) enum UiText {
    Sources,
    Synthetic,
    Real,
    RefreshCameras,
    DiscoveringCameras,
    NoCameras,
    Scene,
    Unsaved,
    Save,
    Layout,
    Grid,
    Row,
    Column,
    Scaling,
    Fast,
    Smooth,
    TargetFps,
    Auto,
    Start,
    Stop,
    Render,
    Output,
    VirtualCamera,
    Setup,
    Ready,
    Paused,
    PreviewRunning,
    WaitingForCamera,
    NoPreview,
    Transform,
    MissingPolicy,
    Placeholder,
    FreezeBriefly,
    HideCell,
    StopOutput,
    Fit,
    Fill,
    Rotation,
    Opacity,
    Position,
    Crop,
    MirrorHorizontal,
    MirrorVertical,
    Reset,
    ExportFrame,
    Diagnostics,
    Language,
    HighContrast,
    SystemExtension,
    SceneFile,
    Validate,
    Import,
    Export,
    Ok,
    Wait,
    Retry,
    Missing,
    Undo,
    Redo,
    VirtualCameraSelfTest,
    Testing,
    RunSelfTest,
    NotRun,
    StopPreviewBeforeTesting,
    Copy,
    CopyDiagnostics,
    CopyTransportEndpoint,
    DismissError,
    RetryCamera,
    MoveEarlier,
    MoveLater,
    SelectSource,
    SourceHealth,
    PublishingTestPattern,
    WaitingForConsumer,
    SelfTestPassed,
    Generation,
    Sequence,
    ApplicationLocation,
    SigningTeamId,
    ExtensionProfile,
    HostProfileMissing,
    HostProfileValid,
    HostProfileInvalid,
    ActivationCapabilityReady,
    ActivationCapability,
    Unavailable,
    Embedded,
    MissingValue,
    ProductionProfileHint,
    InstallExtension,
    Requesting,
    AwaitingApproval,
    Installed,
    RestartRequired,
    RetryActivation,
    CurrentRequestMustFinish,
    InstallSignedBundleFirst,
    ActivationNotRequested,
    RequestingActivation,
    ApproveInSettings,
    ExtensionActivated,
    ActivatesAfterReboot,
    ActivationFailed,
    OpenApprovalInstructions,
    SigningTroubleshooting,
    BareExecutable,
    DevelopmentBundle,
    ApplicationsBundle,
    Live,
    Off,
    TransportEndpointCopied,
    DiagnosticsCopied,
    SelectAtLeastOneSource,
    StartStop,
    NothingToExport,
    FrameExportPath,
    SourceMissingOrStale,
    SceneApplied,
    SceneSaved,
    NamedScene,
    ResetTransform,
    SceneValid,
    SceneExported,
    SceneImported,
    Cancel,
    DiscoveryCancelled,
    SelfTestCancelled,
    ExportingFrame,
    CancellingFrameExport,
    ExportRedactedDiagnostics,
    ExportingDiagnostics,
    CancellingDiagnosticsExport,
    NoSourcesSelected,
    SelectSourceToBegin,
    CameraDisconnected,
    ReconnectCamera,
    CameraNotResponding,
}

impl UiText {
    #[cfg(test)]
    const ALL: &'static [Self] = &[
        Self::Sources,
        Self::Synthetic,
        Self::Real,
        Self::RefreshCameras,
        Self::DiscoveringCameras,
        Self::NoCameras,
        Self::Scene,
        Self::Unsaved,
        Self::Save,
        Self::Layout,
        Self::Grid,
        Self::Row,
        Self::Column,
        Self::Scaling,
        Self::Fast,
        Self::Smooth,
        Self::TargetFps,
        Self::Auto,
        Self::Start,
        Self::Stop,
        Self::Render,
        Self::Output,
        Self::VirtualCamera,
        Self::Setup,
        Self::Ready,
        Self::Paused,
        Self::PreviewRunning,
        Self::WaitingForCamera,
        Self::NoPreview,
        Self::Transform,
        Self::MissingPolicy,
        Self::Placeholder,
        Self::FreezeBriefly,
        Self::HideCell,
        Self::StopOutput,
        Self::Fit,
        Self::Fill,
        Self::Rotation,
        Self::Opacity,
        Self::Position,
        Self::Crop,
        Self::MirrorHorizontal,
        Self::MirrorVertical,
        Self::Reset,
        Self::ExportFrame,
        Self::Diagnostics,
        Self::Language,
        Self::HighContrast,
        Self::SystemExtension,
        Self::SceneFile,
        Self::Validate,
        Self::Import,
        Self::Export,
        Self::Ok,
        Self::Wait,
        Self::Retry,
        Self::Missing,
        Self::Undo,
        Self::Redo,
        Self::VirtualCameraSelfTest,
        Self::Testing,
        Self::RunSelfTest,
        Self::NotRun,
        Self::StopPreviewBeforeTesting,
        Self::Copy,
        Self::CopyDiagnostics,
        Self::CopyTransportEndpoint,
        Self::DismissError,
        Self::RetryCamera,
        Self::MoveEarlier,
        Self::MoveLater,
        Self::SelectSource,
        Self::SourceHealth,
        Self::PublishingTestPattern,
        Self::WaitingForConsumer,
        Self::SelfTestPassed,
        Self::Generation,
        Self::Sequence,
        Self::ApplicationLocation,
        Self::SigningTeamId,
        Self::ExtensionProfile,
        Self::HostProfileMissing,
        Self::HostProfileValid,
        Self::HostProfileInvalid,
        Self::ActivationCapabilityReady,
        Self::ActivationCapability,
        Self::Unavailable,
        Self::Embedded,
        Self::MissingValue,
        Self::ProductionProfileHint,
        Self::InstallExtension,
        Self::Requesting,
        Self::AwaitingApproval,
        Self::Installed,
        Self::RestartRequired,
        Self::RetryActivation,
        Self::CurrentRequestMustFinish,
        Self::InstallSignedBundleFirst,
        Self::ActivationNotRequested,
        Self::RequestingActivation,
        Self::ApproveInSettings,
        Self::ExtensionActivated,
        Self::ActivatesAfterReboot,
        Self::ActivationFailed,
        Self::OpenApprovalInstructions,
        Self::SigningTroubleshooting,
        Self::BareExecutable,
        Self::DevelopmentBundle,
        Self::ApplicationsBundle,
        Self::Live,
        Self::Off,
        Self::TransportEndpointCopied,
        Self::DiagnosticsCopied,
        Self::SelectAtLeastOneSource,
        Self::StartStop,
        Self::NothingToExport,
        Self::FrameExportPath,
        Self::SourceMissingOrStale,
        Self::SceneApplied,
        Self::SceneSaved,
        Self::NamedScene,
        Self::ResetTransform,
        Self::SceneValid,
        Self::SceneExported,
        Self::SceneImported,
        Self::Cancel,
        Self::DiscoveryCancelled,
        Self::SelfTestCancelled,
        Self::ExportingFrame,
        Self::CancellingFrameExport,
        Self::ExportRedactedDiagnostics,
        Self::ExportingDiagnostics,
        Self::CancellingDiagnosticsExport,
        Self::NoSourcesSelected,
        Self::SelectSourceToBegin,
        Self::CameraDisconnected,
        Self::ReconnectCamera,
        Self::CameraNotResponding,
    ];
}

pub(super) fn tr(locale: UiLocale, text: UiText) -> &'static str {
    match (locale, text) {
        (UiLocale::PseudoLong, text) => pseudo_long(text),
        (UiLocale::English, UiText::Sources) => "Sources",
        (UiLocale::Russian, UiText::Sources) => "Источники",
        (UiLocale::English, UiText::Synthetic) => "Synthetic",
        (UiLocale::Russian, UiText::Synthetic) => "Тестовые",
        (UiLocale::English, UiText::Real) => "Cameras",
        (UiLocale::Russian, UiText::Real) => "Камеры",
        (UiLocale::English, UiText::RefreshCameras) => "Refresh cameras",
        (UiLocale::Russian, UiText::RefreshCameras) => "Обновить камеры",
        (UiLocale::English, UiText::DiscoveringCameras) => "Discovering cameras",
        (UiLocale::Russian, UiText::DiscoveringCameras) => "Поиск камер",
        (UiLocale::English, UiText::NoCameras) => "No cameras found",
        (UiLocale::Russian, UiText::NoCameras) => "Камеры не найдены",
        (UiLocale::English, UiText::Scene) => "Scene",
        (UiLocale::Russian, UiText::Scene) => "Сцена",
        (UiLocale::English, UiText::Unsaved) => "Unsaved",
        (UiLocale::Russian, UiText::Unsaved) => "Не сохранена",
        (UiLocale::English, UiText::Save) => "Save",
        (UiLocale::Russian, UiText::Save) => "Сохранить",
        (UiLocale::English, UiText::Layout) => "Layout",
        (UiLocale::Russian, UiText::Layout) => "Раскладка",
        (UiLocale::English, UiText::Grid) => "Grid",
        (UiLocale::Russian, UiText::Grid) => "Сетка",
        (UiLocale::English, UiText::Row) => "Row",
        (UiLocale::Russian, UiText::Row) => "Ряд",
        (UiLocale::English, UiText::Column) => "Column",
        (UiLocale::Russian, UiText::Column) => "Колонка",
        (UiLocale::English, UiText::Scaling) => "Scaling",
        (UiLocale::Russian, UiText::Scaling) => "Масштаб",
        (UiLocale::English, UiText::Fast) => "Fast",
        (UiLocale::Russian, UiText::Fast) => "Быстро",
        (UiLocale::English, UiText::Smooth) => "Smooth",
        (UiLocale::Russian, UiText::Smooth) => "Плавно",
        (UiLocale::English, UiText::TargetFps) => "Target FPS",
        (UiLocale::Russian, UiText::TargetFps) => "Частота кадров",
        (UiLocale::English, UiText::Auto) => "Auto",
        (UiLocale::Russian, UiText::Auto) => "Авто",
        (UiLocale::English, UiText::Start) => "Start",
        (UiLocale::Russian, UiText::Start) => "Старт",
        (UiLocale::English, UiText::Stop) => "Stop",
        (UiLocale::Russian, UiText::Stop) => "Стоп",
        (UiLocale::English, UiText::Render) => "Render",
        (UiLocale::Russian, UiText::Render) => "Кадр",
        (UiLocale::English, UiText::Output) => "Output",
        (UiLocale::Russian, UiText::Output) => "Выход",
        (UiLocale::English, UiText::VirtualCamera) => "Virtual camera",
        (UiLocale::Russian, UiText::VirtualCamera) => "Виртуальная камера",
        (UiLocale::English, UiText::Setup) => "Setup",
        (UiLocale::Russian, UiText::Setup) => "Настройка",
        (UiLocale::English, UiText::Ready) => "Ready",
        (UiLocale::Russian, UiText::Ready) => "Готово",
        (UiLocale::English, UiText::Paused) => "Paused",
        (UiLocale::Russian, UiText::Paused) => "Пауза",
        (UiLocale::English, UiText::PreviewRunning) => "Preview running",
        (UiLocale::Russian, UiText::PreviewRunning) => "Предпросмотр запущен",
        (UiLocale::English, UiText::WaitingForCamera) => "Waiting for camera frame",
        (UiLocale::Russian, UiText::WaitingForCamera) => "Ожидание кадра с камеры",
        (UiLocale::English, UiText::NoPreview) => "No preview",
        (UiLocale::Russian, UiText::NoPreview) => "Нет предпросмотра",
        (UiLocale::English, UiText::Transform) => "Transform",
        (UiLocale::Russian, UiText::Transform) => "Преобразование",
        (UiLocale::English, UiText::MissingPolicy) => "Missing source",
        (UiLocale::Russian, UiText::MissingPolicy) => "Нет источника",
        (UiLocale::English, UiText::Placeholder) => "Placeholder",
        (UiLocale::Russian, UiText::Placeholder) => "Заглушка",
        (UiLocale::English, UiText::FreezeBriefly) => "Freeze briefly",
        (UiLocale::Russian, UiText::FreezeBriefly) => "Короткая пауза",
        (UiLocale::English, UiText::HideCell) => "Hide cell",
        (UiLocale::Russian, UiText::HideCell) => "Скрыть ячейку",
        (UiLocale::English, UiText::StopOutput) => "Stop output",
        (UiLocale::Russian, UiText::StopOutput) => "Остановить выход",
        (UiLocale::English, UiText::Fit) => "Fit",
        (UiLocale::Russian, UiText::Fit) => "Вписать",
        (UiLocale::English, UiText::Fill) => "Fill",
        (UiLocale::Russian, UiText::Fill) => "Заполнить",
        (UiLocale::English, UiText::Rotation) => "Rotation",
        (UiLocale::Russian, UiText::Rotation) => "Поворот",
        (UiLocale::English, UiText::Opacity) => "Opacity",
        (UiLocale::Russian, UiText::Opacity) => "Прозрачность",
        (UiLocale::English, UiText::Position) => "Position",
        (UiLocale::Russian, UiText::Position) => "Позиция",
        (UiLocale::English, UiText::Crop) => "Crop",
        (UiLocale::Russian, UiText::Crop) => "Обрезка",
        (UiLocale::English, UiText::MirrorHorizontal) => "Mirror horizontal",
        (UiLocale::Russian, UiText::MirrorHorizontal) => "Отразить по горизонтали",
        (UiLocale::English, UiText::MirrorVertical) => "Mirror vertical",
        (UiLocale::Russian, UiText::MirrorVertical) => "Отразить по вертикали",
        (UiLocale::English, UiText::Reset) => "Reset",
        (UiLocale::Russian, UiText::Reset) => "Сбросить",
        (UiLocale::English, UiText::ExportFrame) => "Export frame",
        (UiLocale::Russian, UiText::ExportFrame) => "Экспорт кадра",
        (UiLocale::English, UiText::Diagnostics) => "Diagnostics",
        (UiLocale::Russian, UiText::Diagnostics) => "Диагностика",
        (UiLocale::English, UiText::Language) => "Language",
        (UiLocale::Russian, UiText::Language) => "Язык",
        (UiLocale::English, UiText::HighContrast) => "High contrast",
        (UiLocale::Russian, UiText::HighContrast) => "Высокий контраст",
        (UiLocale::English, UiText::SystemExtension) => "System extension",
        (UiLocale::Russian, UiText::SystemExtension) => "Системное расширение",
        (UiLocale::English, UiText::SceneFile) => "Scene file",
        (UiLocale::Russian, UiText::SceneFile) => "Файл сцены",
        (UiLocale::English, UiText::Validate) => "Validate",
        (UiLocale::Russian, UiText::Validate) => "Проверить",
        (UiLocale::English, UiText::Import) => "Import",
        (UiLocale::Russian, UiText::Import) => "Импорт",
        (UiLocale::English, UiText::Export) => "Export",
        (UiLocale::Russian, UiText::Export) => "Экспорт",
        (UiLocale::English, UiText::Ok) => "OK",
        (UiLocale::Russian, UiText::Ok) => "OK",
        (UiLocale::English, UiText::Wait) => "WAIT",
        (UiLocale::Russian, UiText::Wait) => "ЖДЕМ",
        (UiLocale::English, UiText::Retry) => "RETRY",
        (UiLocale::Russian, UiText::Retry) => "ПОВТОР",
        (UiLocale::English, UiText::Missing) => "MISSING",
        (UiLocale::Russian, UiText::Missing) => "НЕТ",
        (UiLocale::English, UiText::Undo) => "Undo",
        (UiLocale::Russian, UiText::Undo) => "Отменить",
        (UiLocale::English, UiText::Redo) => "Redo",
        (UiLocale::Russian, UiText::Redo) => "Повторить",
        (UiLocale::English, UiText::VirtualCameraSelfTest) => "Virtual camera self-test",
        (UiLocale::Russian, UiText::VirtualCameraSelfTest) => "Проверка виртуальной камеры",
        (UiLocale::English, UiText::Testing) => "Testing...",
        (UiLocale::Russian, UiText::Testing) => "Проверка...",
        (UiLocale::English, UiText::RunSelfTest) => "Run self-test",
        (UiLocale::Russian, UiText::RunSelfTest) => "Запустить проверку",
        (UiLocale::English, UiText::NotRun) => "Not run",
        (UiLocale::Russian, UiText::NotRun) => "Не запускалась",
        (UiLocale::English, UiText::StopPreviewBeforeTesting) => {
            "Stop the live preview before testing"
        }
        (UiLocale::Russian, UiText::StopPreviewBeforeTesting) => {
            "Остановите предпросмотр перед проверкой"
        }
        (UiLocale::English, UiText::Copy) => "Copy",
        (UiLocale::Russian, UiText::Copy) => "Копировать",
        (UiLocale::English, UiText::CopyDiagnostics) => "Copy diagnostics",
        (UiLocale::Russian, UiText::CopyDiagnostics) => "Копировать диагностику",
        (UiLocale::English, UiText::CopyTransportEndpoint) => "Copy transport endpoint",
        (UiLocale::Russian, UiText::CopyTransportEndpoint) => "Копировать адрес транспорта",
        (UiLocale::English, UiText::DismissError) => "Dismiss error",
        (UiLocale::Russian, UiText::DismissError) => "Закрыть ошибку",
        (UiLocale::English, UiText::RetryCamera) => "Retry this camera now",
        (UiLocale::Russian, UiText::RetryCamera) => "Повторить подключение камеры",
        (UiLocale::English, UiText::MoveEarlier) => "Move source earlier",
        (UiLocale::Russian, UiText::MoveEarlier) => "Переместить источник выше",
        (UiLocale::English, UiText::MoveLater) => "Move source later",
        (UiLocale::Russian, UiText::MoveLater) => "Переместить источник ниже",
        (UiLocale::English, UiText::SelectSource) => "Select",
        (UiLocale::Russian, UiText::SelectSource) => "Выбрать",
        (UiLocale::English, UiText::SourceHealth) => "Source health",
        (UiLocale::Russian, UiText::SourceHealth) => "Состояние источника",
        (UiLocale::English, UiText::PublishingTestPattern) => "Publishing test pattern",
        (UiLocale::Russian, UiText::PublishingTestPattern) => "Публикация тестового кадра",
        (UiLocale::English, UiText::WaitingForConsumer) => "Waiting for consumer",
        (UiLocale::Russian, UiText::WaitingForConsumer) => "Ожидание потребителя",
        (UiLocale::English, UiText::SelfTestPassed) => "Passed",
        (UiLocale::Russian, UiText::SelfTestPassed) => "Проверка пройдена",
        (UiLocale::English, UiText::Generation) => "generation",
        (UiLocale::Russian, UiText::Generation) => "поколение",
        (UiLocale::English, UiText::Sequence) => "sequence",
        (UiLocale::Russian, UiText::Sequence) => "кадр",
        (UiLocale::English, UiText::ApplicationLocation) => "Application location",
        (UiLocale::Russian, UiText::ApplicationLocation) => "Расположение приложения",
        (UiLocale::English, UiText::SigningTeamId) => "Signing Team ID",
        (UiLocale::Russian, UiText::SigningTeamId) => "Team ID подписи",
        (UiLocale::English, UiText::ExtensionProfile) => "Extension profile",
        (UiLocale::Russian, UiText::ExtensionProfile) => "Профиль расширения",
        (UiLocale::English, UiText::HostProfileMissing) => "Host provisioning profile: missing",
        (UiLocale::Russian, UiText::HostProfileMissing) => "Профиль приложения: отсутствует",
        (UiLocale::English, UiText::HostProfileValid) => "Host provisioning profile: valid",
        (UiLocale::Russian, UiText::HostProfileValid) => "Профиль приложения: действителен",
        (UiLocale::English, UiText::HostProfileInvalid) => "Host provisioning profile: invalid",
        (UiLocale::Russian, UiText::HostProfileInvalid) => "Профиль приложения: недействителен",
        (UiLocale::English, UiText::ActivationCapabilityReady) => "Activation capability: ready",
        (UiLocale::Russian, UiText::ActivationCapabilityReady) => "Активация: готова",
        (UiLocale::English, UiText::ActivationCapability) => "Activation capability",
        (UiLocale::Russian, UiText::ActivationCapability) => "Активация",
        (UiLocale::English, UiText::Unavailable) => "unavailable",
        (UiLocale::Russian, UiText::Unavailable) => "недоступно",
        (UiLocale::English, UiText::Embedded) => "embedded",
        (UiLocale::Russian, UiText::Embedded) => "встроен",
        (UiLocale::English, UiText::MissingValue) => "missing",
        (UiLocale::Russian, UiText::MissingValue) => "отсутствует",
        (UiLocale::English, UiText::ProductionProfileHint) => {
            "Set CAMERAMAN_PROVISIONING_PROFILE for a production bundle."
        }
        (UiLocale::Russian, UiText::ProductionProfileHint) => {
            "Укажите CAMERAMAN_PROVISIONING_PROFILE для production-сборки."
        }
        (UiLocale::English, UiText::InstallExtension) => "Install extension",
        (UiLocale::Russian, UiText::InstallExtension) => "Установить расширение",
        (UiLocale::English, UiText::Requesting) => "Requesting...",
        (UiLocale::Russian, UiText::Requesting) => "Отправка запроса...",
        (UiLocale::English, UiText::AwaitingApproval) => "Awaiting approval",
        (UiLocale::Russian, UiText::AwaitingApproval) => "Ожидание разрешения",
        (UiLocale::English, UiText::Installed) => "Installed",
        (UiLocale::Russian, UiText::Installed) => "Установлено",
        (UiLocale::English, UiText::RestartRequired) => "Restart required",
        (UiLocale::Russian, UiText::RestartRequired) => "Нужна перезагрузка",
        (UiLocale::English, UiText::RetryActivation) => "Retry activation",
        (UiLocale::Russian, UiText::RetryActivation) => "Повторить активацию",
        (UiLocale::English, UiText::CurrentRequestMustFinish) => {
            "The current activation request must finish first."
        }
        (UiLocale::Russian, UiText::CurrentRequestMustFinish) => {
            "Сначала дождитесь завершения текущего запроса."
        }
        (UiLocale::English, UiText::InstallSignedBundleFirst) => {
            "Install a signed production bundle in /Applications first."
        }
        (UiLocale::Russian, UiText::InstallSignedBundleFirst) => {
            "Сначала установите подписанную production-сборку в /Applications."
        }
        (UiLocale::English, UiText::ActivationNotRequested) => "Extension not requested yet",
        (UiLocale::Russian, UiText::ActivationNotRequested) => "Расширение ещё не запрашивалось",
        (UiLocale::English, UiText::RequestingActivation) => "Requesting extension activation...",
        (UiLocale::Russian, UiText::RequestingActivation) => "Запрос активации расширения...",
        (UiLocale::English, UiText::ApproveInSettings) => {
            "Approve the extension in System Settings > General > Login Items & Extensions"
        }
        (UiLocale::Russian, UiText::ApproveInSettings) => {
            "Разрешите расширение в Системных настройках > Основные > Объекты входа и расширения"
        }
        (UiLocale::English, UiText::ExtensionActivated) => "Extension activated",
        (UiLocale::Russian, UiText::ExtensionActivated) => "Расширение активировано",
        (UiLocale::English, UiText::ActivatesAfterReboot) => {
            "Extension will activate after the next reboot"
        }
        (UiLocale::Russian, UiText::ActivatesAfterReboot) => {
            "Расширение активируется после перезагрузки"
        }
        (UiLocale::English, UiText::ActivationFailed) => "Extension activation failed",
        (UiLocale::Russian, UiText::ActivationFailed) => "Не удалось активировать расширение",
        (UiLocale::English, UiText::OpenApprovalInstructions) => "Open approval instructions",
        (UiLocale::Russian, UiText::OpenApprovalInstructions) => "Открыть инструкцию по разрешению",
        (UiLocale::English, UiText::SigningTroubleshooting) => "Signing troubleshooting",
        (UiLocale::Russian, UiText::SigningTroubleshooting) => "Решение проблем с подписью",
        (UiLocale::English, UiText::BareExecutable) => "bare executable",
        (UiLocale::Russian, UiText::BareExecutable) => "отдельный исполняемый файл",
        (UiLocale::English, UiText::DevelopmentBundle) => "development .app",
        (UiLocale::Russian, UiText::DevelopmentBundle) => "development .app",
        (UiLocale::English, UiText::ApplicationsBundle) => "Applications .app",
        (UiLocale::Russian, UiText::ApplicationsBundle) => ".app в Applications",
        (UiLocale::English, UiText::Live) => "LIVE",
        (UiLocale::Russian, UiText::Live) => "ЭФИР",
        (UiLocale::English, UiText::Off) => "OFF",
        (UiLocale::Russian, UiText::Off) => "ВЫКЛ",
        (UiLocale::English, UiText::TransportEndpointCopied) => "Transport endpoint copied",
        (UiLocale::Russian, UiText::TransportEndpointCopied) => "Адрес транспорта скопирован",
        (UiLocale::English, UiText::DiagnosticsCopied) => "Diagnostics copied",
        (UiLocale::Russian, UiText::DiagnosticsCopied) => "Диагностика скопирована",
        (UiLocale::English, UiText::SelectAtLeastOneSource) => "Select at least one source",
        (UiLocale::Russian, UiText::SelectAtLeastOneSource) => "Выберите хотя бы один источник",
        (UiLocale::English, UiText::StartStop) => "Start or stop (Space)",
        (UiLocale::Russian, UiText::StartStop) => "Старт или стоп (Пробел)",
        (UiLocale::English, UiText::NothingToExport) => "Nothing to export yet",
        (UiLocale::Russian, UiText::NothingToExport) => "Пока нечего экспортировать",
        (UiLocale::English, UiText::FrameExportPath) => "Frame export path",
        (UiLocale::Russian, UiText::FrameExportPath) => "Путь экспорта кадра",
        (UiLocale::English, UiText::SourceMissingOrStale) => {
            "One or more selected sources are missing or stale"
        }
        (UiLocale::Russian, UiText::SourceMissingOrStale) => {
            "Один или несколько источников отсутствуют или устарели"
        }
        (UiLocale::English, UiText::SceneApplied) => "Scene applied",
        (UiLocale::Russian, UiText::SceneApplied) => "Сцена применена",
        (UiLocale::English, UiText::SceneSaved) => "Scene saved",
        (UiLocale::Russian, UiText::SceneSaved) => "Сцена сохранена",
        (UiLocale::English, UiText::NamedScene) => "Named scene",
        (UiLocale::Russian, UiText::NamedScene) => "Название сцены",
        (UiLocale::English, UiText::ResetTransform) => "Reset selected source transform",
        (UiLocale::Russian, UiText::ResetTransform) => "Сбросить преобразование источника",
        (UiLocale::English, UiText::SceneValid) => "Scene JSON is valid",
        (UiLocale::Russian, UiText::SceneValid) => "JSON сцены корректен",
        (UiLocale::English, UiText::SceneExported) => "Scene exported",
        (UiLocale::Russian, UiText::SceneExported) => "Сцена экспортирована",
        (UiLocale::English, UiText::SceneImported) => "Scene imported",
        (UiLocale::Russian, UiText::SceneImported) => "Сцена импортирована",
        (UiLocale::English, UiText::Cancel) => "Cancel",
        (UiLocale::Russian, UiText::Cancel) => "Отмена",
        (UiLocale::English, UiText::DiscoveryCancelled) => "Camera discovery cancelled",
        (UiLocale::Russian, UiText::DiscoveryCancelled) => "Поиск камер отменён",
        (UiLocale::English, UiText::SelfTestCancelled) => "Virtual camera self-test cancelled",
        (UiLocale::Russian, UiText::SelfTestCancelled) => "Проверка виртуальной камеры отменена",
        (UiLocale::English, UiText::ExportingFrame) => "Exporting frame",
        (UiLocale::Russian, UiText::ExportingFrame) => "Экспорт кадра",
        (UiLocale::English, UiText::CancellingFrameExport) => "Cancelling frame export",
        (UiLocale::Russian, UiText::CancellingFrameExport) => "Отмена экспорта кадра",
        (UiLocale::English, UiText::ExportRedactedDiagnostics) => "Export redacted diagnostics",
        (UiLocale::Russian, UiText::ExportRedactedDiagnostics) => {
            "Экспорт диагностики без личных данных"
        }
        (UiLocale::English, UiText::ExportingDiagnostics) => "Exporting diagnostics",
        (UiLocale::Russian, UiText::ExportingDiagnostics) => "Экспорт диагностики",
        (UiLocale::English, UiText::CancellingDiagnosticsExport) => "Cancelling diagnostics export",
        (UiLocale::Russian, UiText::CancellingDiagnosticsExport) => "Отмена экспорта диагностики",
        (UiLocale::English, UiText::NoSourcesSelected) => "No sources selected",
        (UiLocale::Russian, UiText::NoSourcesSelected) => "Источники не выбраны",
        (UiLocale::English, UiText::SelectSourceToBegin) => {
            "Select a source in the Sources panel to begin"
        }
        (UiLocale::Russian, UiText::SelectSourceToBegin) => {
            "Выберите источник в панели «Источники»"
        }
        (UiLocale::English, UiText::CameraDisconnected) => "Camera disconnected",
        (UiLocale::Russian, UiText::CameraDisconnected) => "Камера отключена",
        (UiLocale::English, UiText::ReconnectCamera) => {
            "Reconnect the camera, then refresh the source list"
        }
        (UiLocale::Russian, UiText::ReconnectCamera) => {
            "Подключите камеру и обновите список источников"
        }
        (UiLocale::English, UiText::CameraNotResponding) => "Camera is not responding",
        (UiLocale::Russian, UiText::CameraNotResponding) => "Камера не отвечает",
    }
}

fn pseudo_long(text: UiText) -> &'static str {
    static CACHE: OnceLock<Mutex<HashMap<UiText, &'static str>>> = OnceLock::new();
    let cache = CACHE.get_or_init(|| Mutex::new(HashMap::new()));
    let mut cache = cache
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner());
    if let Some(value) = cache.get(&text) {
        return value;
    }
    let base = tr(UiLocale::English, text);
    let expanded = Box::leak(format!("[!! {base} / {base} !!]").into_boxed_str());
    cache.insert(text, expanded);
    expanded
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_key_has_nonempty_english_and_russian_fixture_text() {
        for &key in UiText::ALL {
            assert!(!tr(UiLocale::English, key).is_empty());
            assert!(!tr(UiLocale::Russian, key).is_empty());
            assert!(tr(UiLocale::PseudoLong, key).len() > tr(UiLocale::English, key).len());
        }
    }
}
